title: DIY GPS App bundle
author: Csaba Toth
email: csaba.toth.us@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  About Do-It-Yourself GPS App bundle

twitter_username: tocsa2
github_username:  MrCsabaToth

google_analytics: G-ZQ9QTJR3J7

tracker:
  app_url: https://play.google.com/store/apps/details?id=dev.csaba.diygpstracker
  src_url: https://github.com/DIYGPSTracker/DIYGPSTracker

manager:
  app_url: https://play.google.com/store/apps/details?id=dev.csaba.diygpsmanager
  src_url: https://github.com/DIYGPSTracker/DIYGPSManager

messaging:
  src_url: https://github.com/DIYGPSTracker/DIYGPSMessaging

exclude:
  - "LICENSE"
  - "README.md"
  - ".gitignore"
plugins:
  - jekyll-redirect-from

sass:
    style: compressed
theme: jekyll-theme-minimal
